### ISSUE TITLE
Remove Eurostat NULL columns

### ISSUE THREAD

**Issue by antoniocarlon** [CartoDB/bigmetadata#347]
In Eurostat there are a lot of _flag columns. We should remove the _flag fields, which only indicate if there is data for the associated field. They have also weight=0 so they do not show in output.

Related to https://github.com/CartoDB/bigmetadata/pull/337
See https://github.com/CartoDB/bigmetadata/pull/337#issuecomment-335511353

**Comment by antoniocarlon** [comment]
**Note for the acceptance:** I have seen several null columns in the ETL machine that hasn't raised in local execution. Maybe this is because ETL tables need to be re-ANALYZED, but if you find errors due to null columns during acceptance, please send this issue back to development.

**Comment by ethervoid** [comment]
Wait until the ETL machine is free

**Comment by ethervoid** [comment]
### Acceptance

Found an error while exectuing this `tasks.eu.eurostat.TableEU(table_name=ILC_LVHL21, subsection=employment, nuts_level=2, unit=people, year=2016)`

**Comment by antoniocarlon** [comment]
Removed the columns `ilc_lvhl21_pc_lw95` and `ilc_lvhl21_pc_up95` when `subsection=employment` and `nuts_level=2` and `unit=people`

**Comment by ethervoid** [comment]
Another one:

```
ERROR: [pid 1] Worker Worker(salt=796835113, workers=1, host=9dd6e81d0357, username=root, pid=1) failed    tasks.eu.eurostat.TableEU(table_name=EDUC_RENRLRG1, subsection=education, nuts_level=2, unit=people, year=2003)^M
Traceback (most recent call last):^M
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 194, in run^M
    new_deps = self._run_get_new_deps()^M
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 131, in _run_get_new_deps^M
    task_gen = self.task.run()^M
  File "/bigmetadata/tasks/util.py", line 1603, in run^M
    self.check_null_columns()^M
  File "/bigmetadata/tasks/util.py", line 1659, in check_null_columns^M
    table=self.output().table, columns=', '.join([x[0] for x in result])))^M
ValueError: The following columns of the table "observatory.obs_0070b2c8bae3d72bac7648713e31eae7effe6af9" contain only NULL values: educ_renrlrg1_f_ed3_g_nr, educ_renrlrg1_m_ed3_g_nr, educ_renrlrg1_t_ed3_g_nr, educ_renrlrg1_f_ed3_vpv_nr, educ_renrlrg1_m_ed3_vpv_nr, educ_renrlrg1_t_ed3_vpv_nr, educ_renrlrg1_f_ed4_g_nr, educ_renrlrg1_m_ed4_g_nr, educ_renrlrg1_t_ed4_g_nr, educ_renrlrg1_f_ed4_vpv_nr, educ_renrlrg1_m_ed4_vpv_nr, educ_renrlrg1_t_ed4_vpv_nr^M
rollback tasks.eu.eurostat.TableEU_2_education_EDUC_RENRLRG1_773fd46892: The following columns of the table "observatory.obs_0070b2c8bae3d72bac7648713e31eae7effe6af9" contain only NULL values: educ_renrlrg1_f_ed3_g_nr, educ_renrlrg1_m_ed3_g_nr, educ_renrlrg1_t_ed3_g_nr, educ_renrlrg1_f_ed3_vpv_nr, educ_renrlrg1_m_ed3_vpv_nr, educ_renrlrg1_t_ed3_vpv_nr, educ_renrlrg1_f_ed4_g_nr, educ_renrlrg1_m_ed4_g_nr, educ_renrlrg1_t_ed4_g_nr, educ_renrlrg1_f_ed4_vpv_nr, educ_renrlrg1_m_ed4_vpv_nr, educ_renrlrg1_t_ed4_vpv_nr^M
INFO: Informed scheduler that task   tasks.eu.eurostat.TableEU_2_education_EDUC_RENRLRG1_773fd46892   has status   FAILED
```

**Comment by antoniocarlon** [comment]
Solved and checked that the resulting table is not empty (has columns)

**Comment by ethervoid** [comment]
Everything working ok now :)
