### ISSUE TITLE
make us-zillow fails

### ISSUE THREAD

**Issue by contra** [CartoDB/bigmetadata#395]
```
2017-12-06 16:47:20,713 update_or_create_metadata
INFO: update_or_create_metadata
2017-12-06 16:47:20,794 time: 0.08082747459411621
INFO: time: 0.08082747459411621
2017-12-06 16:47:20,795 analyzing the table observatory.obs_14e64ddb2ed26f90ab9cd8e64bbaa3bee6ec56ea
INFO: analyzing the table observatory.obs_14e64ddb2ed26f90ab9cd8e64bbaa3bee6ec56ea
2017-12-06 16:47:20,870 checking for null columns on observatory.obs_14e64ddb2ed26f90ab9cd8e64bbaa3bee6ec56ea
INFO: checking for null columns on observatory.obs_14e64ddb2ed26f90ab9cd8e64bbaa3bee6ec56ea
2017-12-06 16:47:20,883 checking for medians/averages without universe target on observatory.obs_14e64ddb2ed26f90ab9cd8e64bbaa3bee6ec56ea
INFO: checking for medians/averages without universe target on observatory.obs_14e64ddb2ed26f90ab9cd8e64bbaa3bee6ec56ea
ERROR: [pid 484] Worker Worker(salt=443074754, workers=8, host=16a497932f56, username=root, pid=1) failed    tasks.us.zillow.Zillow(year=2015, month=9, geography=Zip)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 194, in run
    new_deps = self._run_get_new_deps()
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 131, in _run_get_new_deps
    task_gen = self.task.run()
  File "/bigmetadata/tasks/base_tasks.py", line 859, in run
    self.check_universe_in_aggregations()
  File "/bigmetadata/tasks/base_tasks.py", line 932, in check_universe_in_aggregations
    table=self.output().table, columns=', '.join([x[0] for x in result])))
ValueError: The following columns of the table "observatory.obs_14e64ddb2ed26f90ab9cd8e64bbaa3bee6ec56ea" are aggregated as 'median' or 'average' but lack of 'universe' target: us.zillow.Sfr_MedianRentalPricePerSqft, us.zillow.AllHomes_MedianValuePerSqft
```

```
===== Luigi Execution Summary =====

Scheduled 95 tasks of which:
* 9 present dependencies were encountered:
    - 1 tasks.us.census.tiger.GeoidColumns()
    - 7 tasks.us.zillow.WideZillow(...)
    - 1 tasks.us.zillow.ZillowValueColumns()
* 85 failed:
    - 85 tasks.us.zillow.Zillow(year=2010, month=11, geography=Zip) ...
* 1 were left pending, among these:
    * 1 had failed dependencies:
        - 1 tasks.us.zillow.AllZillow()

This progress looks :( because there were failed tasks
```

**Comment by antoniocarlon** [comment]
**Note for the acceptance:** `make us-zillow` may fail if Zillow hasn't released last month data.
