### ISSUE TITLE
Eurostat is failing to download a file

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/bigmetadata#426]
Related #412 

```
ERROR: [pid 1] Worker Worker(salt=900995649, workers=1, host=deceeebc7ab2, username=root, pid=1) failed    tasks.eu.eurostat.DownloadEurostat(table_code=NAMA_AUX_CRA)^M
Traceback (most recent call last):^M
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 194, in run^M
    new_deps = self._run_get_new_deps()^M
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 131, in _run_get_new_deps^M
    task_gen = self.task.run()^M
  File "/bigmetadata/tasks/eu/eurostat.py", line 39, in run^M
    shell('gunzip {output}.gz'.format(output=self.output().path))^M
  File "/bigmetadata/tasks/util.py", line 31, in shell^M
    return subprocess.check_output(cmd, shell=True, stderr=subprocess.STDOUT).decode(encoding)^M
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output^M
    **kwargs).stdout^M
  File "/usr/lib/python3.5/subprocess.py", line 708, in run^M
    output=stdout, stderr=stderr)^M
subprocess.CalledProcessError: Command 'gunzip tmp/eu.eurostat/tasks.eu.eurostat.DownloadEurostat_NAMA_AUX_CRA_241906624b.gz' returned non-zero exit status 1
 ```

Downloaded file is a HTML that contains this message: `File nama_aux_cra.tsv.gz does not exist or is not readable on the server`

**Comment by ethervoid** [comment]
Seems like Eurostat has changed and data dataset is no longer provided. I haven't seen another equal dataset so I think, by now, the best alternative is to remove that column
