### ISSUE TITLE
UK census scotland failing due to compression failure

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/bigmetadata#433]
Related to #412 

```
ERROR: [pid 1] Worker Worker(salt=194344392, workers=1, host=c00753472036, username=root, pid=1) failed    tasks.uk.census.scotland.DownloadScotlandLocal()^M
Traceback (most recent call last):^M
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 194, in run^M
    new_deps = self._run_get_new_deps()^M
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 131, in _run_get_new_deps^M
    task_gen = self.task.run()^M
  File "/bigmetadata/tasks/base_tasks.py", line 423, in run^M
    self.uncompress()^M
  File "/bigmetadata/tasks/base_tasks.py", line 452, in uncompress^M
    z.extractall(path='{output}'.format(output=self.output().path))^M
  File "/usr/lib/python3.5/zipfile.py", line 1347, in extractall^M
    self.extract(zipinfo, path, pwd)^M
  File "/usr/lib/python3.5/zipfile.py", line 1335, in extract^M
    return self._extract_member(member, path, pwd)^M
  File "/usr/lib/python3.5/zipfile.py", line 1397, in _extract_member^M
    with self.open(member, pwd=pwd) as source, \^M
  File "/usr/lib/python3.5/zipfile.py", line 1318, in open^M
    return ZipExtFile(zef_file, mode, zinfo, zd, True)^M
  File "/usr/lib/python3.5/zipfile.py", line 718, in __init__^M
    self._decompressor = _get_decompressor(self._compress_type)^M
  File "/usr/lib/python3.5/zipfile.py", line 648, in _get_decompressor^M
    raise NotImplementedError("compression type %d (%s)" % (compress_type, descr))^M
NotImplementedError: compression type 9 (deflate64)^M
```

**Comment by antoniocarlon** [comment]
Related to https://github.com/CartoDB/bigmetadata/issues/427
It's fixed and merged now. Could you merge master and test again?

**Comment by ethervoid** [comment]
On it thx!
