### ISSUE TITLE
Brazil is failing due to CSV errors

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/bigmetadata#453]
```
INFO: [pid 3994] Worker Worker(salt=374369173, workers=1, host=23f8f528b7ad, username=root, pid=3994) running   tasks.br.data.ImportData(state=rn, tablename=ResponsavelRenda)
ERROR: b'ERROR:  extra data after last expected column\nCONTEXT:  COPY importdata_rn_responsavelrenda_8e9e884ec1, line 2: "240010905000001;1;4.0;56.0;15.0;3.0;1.0;0.0;0.0;0.0;0.0;8.0;850.0;26912.0;12692.0;4210.0;1800.0;0.0;..."\n'
ERROR: [pid 3994] Worker Worker(salt=374369173, workers=1, host=23f8f528b7ad, username=root, pid=3994) failed    tasks.br.data.ImportData(state=rn, tablename=ResponsavelRenda)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 194, in run
    new_deps = self._run_get_new_deps()
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 131, in _run_get_new_deps
    task_gen = self.task.run()
  File "/bigmetadata/tasks/base_tasks.py", line 716, in run
    options=' '.join(options)
  File "/bigmetadata/tasks/util.py", line 31, in shell
    return subprocess.check_output(cmd, shell=True, stderr=subprocess.STDOUT).decode(encoding)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'cat "tmp/br.data/tasks.br.data.DownloadData_rn_41c927cfd5/ResponsavelRenda_RN.csv" | psql -c '\copy "br.data".ImportData_rn_ResponsavelRenda_8e9e884ec1 FROM STDIN
           DELIMITER '"';'"' ENCODING '"'latin1'"'
         CSV HEADER' ' returned non-zero exit status 1
INFO: Informed scheduler that task   tasks.br.data.ImportData_rn_ResponsavelRenda_8e9e884ec1   has status   FAILED
```

**Comment by ethervoid** [comment]
Now we're getting this new Error:
```
ERROR: [pid 3993] Worker Worker(salt=859079666, workers=1, host=80858fa2a4a5, username=root, pid=3993) failed    tasks.br.data.ImportData(state=es, tablename=ResponsavelRenda)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 194, in run
    new_deps = self._run_get_new_deps()
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 131, in _run_get_new_deps
    task_gen = self.task.run()
  File "/bigmetadata/tasks/base_tasks.py", line 694, in run
    if isinstance(self.input_csv(), str):
  File "/bigmetadata/tasks/br/data.py", line 110, in input_csv
    path = glob.glob(os.path.join(self.input().path, '**', filename), recursive=True)[0]
IndexError: list index out of range
```
@antoniocarlon ^

**Comment by antoniocarlon** [comment]
On it! https://github.com/CartoDB/bigmetadata/issues/456

**Comment by ethervoid** [comment]
Another one 
```
ERROR: [pid 3993] Worker Worker(salt=583821857, workers=1, host=3db7b5004b46, username=root, pid=3993) failed    tasks.br.data.ImportData(state=al, tablename=Pessoa05)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 194, in run
    new_deps = self._run_get_new_deps()
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 131, in _run_get_new_deps
    task_gen = self.task.run()
  File "/bigmetadata/tasks/base_tasks.py", line 694, in run
    if isinstance(self.input_csv(), str):
  File "/bigmetadata/tasks/br/data.py", line 110, in input_csv
    path = glob.glob(os.path.join(self.input().path, '**', filename), recursive=True)[0]
IndexError: list index out of range
```

**Comment by antoniocarlon** [comment]
On it! #458
