### ISSUE TITLE
ACS is failing with PG10

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/bigmetadata#490]
Two failures by now:

```
ERROR: [pid 7011] Worker Worker(salt=945795587, workers=1, host=b54239acb730, username=root, pid=7011) failed    tasks.us.census.acs.Extract(year=2010, sample=1yr, geography=county)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 194, in run
    new_deps = self._run_get_new_deps()
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 131, in _run_get_new_deps
    task_gen = self.task.run()
  File "/bigmetadata/tasks/base_tasks.py", line 918, in run
    self.check_table_to_table_relations()
  File "/bigmetadata/tasks/base_tasks.py", line 1033, in check_table_to_table_relations
    table=self.output().table, relations=', '.join([x[0] for x in result])))
ValueError: The table "observatory.obs_539f1f90236f03c19a33996f46352a20ba7171bc" lacks some table_to_table relations: us.census.acs.extract_county_1yr_2010_1ae9e5a6ac.us.census.tiger.county_geoidsc / us.census.tiger.shoreline_clip_county_2015_c512ae8318.us.census.tiger.county_clipped (geom_ref)
```
and 

```
ERROR: [pid 7011] Worker Worker(salt=945795587, workers=1, host=b54239acb730, username=root, pid=7011) failed    tasks.us.census.acs.Quantiles(year=2014, sample=1yr, geography=school_district_secondary)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1184, in _execute_context
    context)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
psycopg2.NotSupportedError: source for a multiple-column UPDATE item must be a sub-SELECT or ROW() expression
LINE 6: ...e5050218eae0819a3d SET (pop_divorced_quantile) = (pop_divorc...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 194, in run
    new_deps = self._run_get_new_deps()
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 131, in _run_get_new_deps
    task_gen = self.task.run()
  File "/bigmetadata/tasks/base_tasks.py", line 896, in run
    self.populate()
  File "/bigmetadata/tasks/us/census/acs.py", line 3434, in populate
    connection.execute(stmt)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 1044, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 947, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/sql/elements.py", line 262, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1055, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1191, in _execute_context
    context)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1386, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1184, in _execute_context
    context)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.NotSupportedError: (psycopg2.NotSupportedError) source for a multiple-column UPDATE item must be a sub-SELECT or ROW() expression
LINE 6: ...e5050218eae0819a3d SET (pop_divorced_quantile) = (pop_divorc...
                                                             ^
 [SQL: '\n                    WITH data as (\n                        SELECT geoidsl, geoidsc,  percent_rank() OVER (ORDER BY pop_divorced ASC) as pop_divorced \n                        FROM observatory.obs_76dc7922c095132046bd2c94978adbb497b821fc\n                    )\n                    UPDATE observatory.obs_70fb36ddc085a80281218ce5050218eae0819a3d SET (pop_divorced_quantile) = (pop_divorced)\n                    FROM data\n                    WHERE data.geoidsc = observatory.obs_70fb36ddc085a80281218ce5050218eae0819a3d.geoidsc\n                     AND data.geoidsl = observatory.obs_70fb36ddc085a80281218ce5050218eae0819a3d.geoidsl\n                ']
```

**Comment by ethervoid** [comment]
First one is fixed with [this commit](https://github.com/CartoDB/bigmetadata/pull/491/commits/346f1cdc6dd5885d81ed7acc53a62106fd87f0f7)

The second error seems to be a change from PG9 to PG10. More info [here](https://www.postgresql.org/message-id/20170719174507.GA19616%40telsasoft.com)
