### ISSUE TITLE
DO ETL fails

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/bigmetadata#504]
Doing #440 acceptance showed this error for LODES (`make docker-us-lodes`):

```
2018-05-29 10:55:29,057 [ERROR]: [pid 22] Worker Worker(salt=759641377, workers=1, host=6e8aaca1ef54, username=root, pid=22) failed    tasks.us.census.lodes.WorkplaceAreaCharacteristics(year=2013)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 194, in run
    new_deps = self._run_get_new_deps()
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 131, in _run_get_new_deps
    task_gen = self.task.run()
  File "/bigmetadata/tasks/base_tasks.py", line 938, in run
    self.check_table_to_table_relations()
  File "/bigmetadata/tasks/base_tasks.py", line 1053, in check_table_to_table_relations
    table=self.output().table, relations=', '.join([x[0] for x in result])))
ValueError: The table "observatory.obs_5bc83d67ea2863b1712078813a730eee753cf316" lacks some table_to_table relations: us.census.lodes.workplace_area_characteristics_2013_dd20d99063.us.census.tiger.block_geoidsc / us.census.tiger.shoreline_clip_block_2015_51839c2b6d.us.census.tiger.block_clipped (geom_ref)
2018-05-29 10:55:29,088 [INFO]: Informed scheduler that task   tasks.us.census.lodes.WorkplaceAreaCharacteristics_2013_dd20d99063   has status   FAILED
2018-05-29 10:55:29,092 [INFO]: Worker Worker(salt=759641377, workers=1, host=6e8aaca1ef54, username=root, pid=22) was stopped. Shutting down Keep-Alive thread
2018-05-29 10:55:29,109 [INFO]:
===== Luigi Execution Summary =====

Scheduled 109 tasks of which:
* 6 present dependencies were encountered:
    - 1 tasks.base_tasks.CreateRepoTable()
    - 1 tasks.tags.LicenseTags()
    - 1 tasks.tags.SectionTags()
    - 1 tasks.tags.SubsectionTags()
    - 1 tasks.us.census.tiger.GeoidColumns()
    ...
* 101 ran successfully:
    - 49 tasks.base_tasks.RepoFile(resource_id=tasks.us.census.lodes.DownloadUnzipLodes_csv_rac_JT00_02fd206562, url=http://lehd.ces.census.gov/data/lodes/LODES7/ut/rac/ut_rac_S000_JT00_2013.csv.gz, version=1) ...
    - 49 tasks.us.census.lodes.DownloadUnzipLodes(file_extension=csv, year=2013, filetype=rac, state=ak, partorsegment=S000, jobtype=JT00) ...
    - 1 tasks.us.census.lodes.SourceTags()
    - 1 tasks.us.census.lodes.WorkplaceAreaCharacteristicsColumns()
    - 1 tasks.us.census.lodes.WorkplaceAreaCharacteristicsTemp(year=2013)
* 1 failed:
    - 1 tasks.us.census.lodes.WorkplaceAreaCharacteristics(year=2013)
* 1 were left pending, among these:
    * 1 had failed dependencies:
        - 1 tasks.us.census.lodes.LODESMetaWrapper(geography=block, year=2013)

This progress looks :( because there were failed tasks
```

cc @antoniocarlon and @ramiroaznar for RT

**Comment by juanignaciosl** [comment]
It blocks not only DO regeneration but also the acceptance of an ongoing issue, so it's blocking our workflow. I'd say that it's less important than current issues opened by customers but more important than any older issue.

**Comment by juanignaciosl** [comment]
New error: `make docker-us-enviroatlas`

```
2018-05-30 07:21:21,577 [INFO]: Informed scheduler that task   tasks.us.epa.enviroatlas.EnviroAtlas_landcover_2006_93f47d1d11   has status   UNKNOWN
2018-05-30 07:21:21,579 [WARNING]: Will not run tasks.us.epa.enviroatlas.EnviroAtlas(table=AvgPrecip, time=2010) or any dependencies due to error in deps() method:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 743, in _add
    deps = task.deps()
  File "/usr/local/lib/python3.5/dist-packages/luigi/task.py", line 630, in deps
    return flatten(self._requires())
  File "/bigmetadata/tasks/base_tasks.py", line 784, in _requires
    reqs = super(TableTask, self)._requires()
  File "/usr/local/lib/python3.5/dist-packages/luigi/task.py", line 602, in _requires
    return flatten(self.requires())  # base impl
  File "/bigmetadata/tasks/us/epa/enviroatlas.py", line 180, in requires
    'geo': HUC(),
NameError: name 'HUC' is not defined
```

**Comment by juanignaciosl** [comment]
I've just finished the remaining task [check the list here](https://github.com/CartoDB/bigmetadata/pull/440#issuecomment-370811750) so now these two issues are actually blocking the acceptance.

@antoniocarlon when you can address this, maybe you can open a PR on `428-Repository_for_DO_ETL_files`, to ease merging.

**Comment by ramiroaznar** [comment]
Should we close this issue?

**Comment by juanignaciosl** [comment]
Yep
