### ISSUE TITLE
EU download is broken

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/bigmetadata#525]
Right now is giving error in the Download task for EU with a 403 forbidden
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 194, in run
    new_deps = self._run_get_new_deps()
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 131, in _run_get_new_deps
    task_gen = self.task.run()
  File "/bigmetadata/tasks/eu/geo.py", line 49, in run
    self.download()
  File "/bigmetadata/tasks/eu/geo.py", line 44, in download
    url=self.URL,
  File "/bigmetadata/tasks/util.py", line 31, in shell
    return subprocess.check_output(cmd, shell=True, stderr=subprocess.STDOUT).decode(encoding)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'wget -O tmp/eu.geo/tasks.eu.geo.DownloadGeographies__99914b932b.7z --referer='xxx' 'http://wxs-telechargement.ign.fr/aoar2g7319l0hi4l42nkzlc5/telechargement/prepackage/EGM_EUROPE_PACK_20151028$EGM_8-0SHP_20151028/file/EGM_8-0SHP_20151028.7z'' returned non-zero exit status 8
```

**Comment by ethervoid** [comment]
Fixed in #526
