### ISSUE TITLE
Error executing `us-all` in production

### ISSUE THREAD

**Issue by antoniocarlon** [CartoDB/bigmetadata#590]
Error executing `us-all` in production:

```
[ERROR]: [pid 20] Worker Worker(salt=308023726, workers=1, host=e8baf99e274c, username=root, pid=20) failed    tasks.us.bls.QCEW(year=2013, qtr=1)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 203, in run
    new_deps = self._run_get_new_deps()
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 140, in _run_get_new_deps
    task_gen = self.task.run()
  File "/bigmetadata/tasks/base_tasks.py", line 906, in run
    output = self.output()
  File "/bigmetadata/tasks/base_tasks.py", line 1113, in output
    self._columns = self.columns()
  File "/bigmetadata/tasks/us/bls.py", line 240, in columns
    ('area_fipssl', input_['geoid_cols']['county' + GEOID_SUMLEVEL_COLUMN]),
KeyError: 'county_geoidsl'
[INFO]: rollback tasks.us.bls.QCEW_1_2013_15999977ce: 'county_geoidsl'
[INFO]: Informed scheduler that task   tasks.us.bls.QCEW_1_2013_15999977ce   has status   FAILED
```

**Comment by ethervoid** [comment]
Ok the problem is that before the change we have `county_geoidsl` and now we have `country_2015_geoisl`

**Comment by ethervoid** [comment]
Updated all the US tasks to use Tiger 2016. 

I've received this error message from ACS

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 203, in run
    new_deps = self._run_get_new_deps()
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 140, in _run_get_new_deps
    task_gen = self.task.run()
  File "/bigmetadata/tasks/base_tasks.py", line 925, in run
    self.populate()
  File "/bigmetadata/tasks/us/census/acs.py", line 216, in populate
    self.populate_general()
  File "/bigmetadata/tasks/us/census/acs.py", line 279, in populate_general
    inputschema=inputschema, inputtable=tableids.pop())
KeyError: 'pop from an empty set'
```

**Comment by ethervoid** [comment]
We have NULL values in some ACS columns:

```
ValueError: The following columns of the table "observatory.obs_aac0fc14df695ac925aec00a0e0c71b7e3895c20" contain only NULL values: pop_5_years_over, speak_only_english_at_home, speak_spanish_at_home, speak_spanish_at_home_low_english
```

**Comment by ethervoid** [comment]
Now the `tasks.us.census.tiger.SplitByState` task is failing due to:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 203, in run
    new_deps = self._run_get_new_deps()
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 140, in _run_get_new_deps
    task_gen = self.task.run()
  File "/bigmetadata/tasks/us/census/tiger.py", line 455, in run
    session.execute(query)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 1044, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 947, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/sql/elements.py", line 262, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1055, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1191, in _execute_context
    context)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1386, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1184, in _execute_context
    context)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "tiger2016.tabblock" does not exist
LINE 4:                 FROM "tiger2016".tabblock
                             ^
 [SQL: '\n                CREATE TABLE "tiger2016".tabblock_state66 AS\n                SELECT *\n                FROM "tiger2016".tabblock\n                WHERE statefp10 = \'66\'\n                ']
```

**Comment by ethervoid** [comment]
I'm regenerating the Tiger 2016 dump file adding the missing table, tabblock. I'm using the scripts used originally for the dump we're using which can be found [here](https://github.com/censusreporter/census-postgres-scripts)

**Comment by javitonino** [comment]
After the latest Zillow fix, `us-all` runs correctly (and is executed in production)
