### ISSUE TITLE
uk.gov.DownloadLowerLayerSuperOutputAreas fails

### ISSUE THREAD

**Issue by javitonino** [CartoDB/bigmetadata#593]
Running this task fails with error:
```
2018-10-30 19:49:22,191 [ERROR]: [pid 1] Worker Worker(salt=319261826, workers=1, host=39ac80fd0214, username=root, pid=1) failed    tasks.uk.gov.DownloadLowerLayerSuperOutputAreas()
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 203, in run
    new_deps = self._run_get_new_deps()
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 140, in _run_get_new_deps
    task_gen = self.task.run()
  File "/bigmetadata/tasks/base_tasks.py", line 441, in run
    self.uncompress()
  File "/bigmetadata/tasks/base_tasks.py", line 469, in uncompress
    uncompress_file(self.output().path)
  File "/bigmetadata/tasks/util.py", line 444, in uncompress_file
    with zipfile.ZipFile('{zip_file}.zip'.format(zip_file=zip_file), 'r') as z:
  File "/usr/lib/python3.5/zipfile.py", line 1026, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.5/zipfile.py", line 1093, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
2018-10-30 19:49:22,221 [INFO]: Informed scheduler that task   tasks.uk.gov.DownloadLowerLayerSuperOutputAreas__99914b932b   has status   FAILED
2018-10-30 19:49:22,228 [INFO]: Worker Worker(salt=319261826, workers=1, host=39ac80fd0214, username=root, pid=1) was stopped. Shutting down Keep-Alive thread
2018-10-30 19:49:22,231 [INFO]:
```

The response from the download file (https://github.com/CartoDB/bigmetadata/blob/master/tasks/uk/gov.py#L29 --> https://opendata.arcgis.com/datasets/da831f80764346889837c72508f046fa_0.zip?outSR=%7B%22wkid%22%3A27700%2C%22latestWkid%22%3A27700%7D) is `{"processingTime":"8.126883333333334 minutes","status":"Processing","count":12000,"generating":{}}` so it seems the server is somehow preparing the file.

**Comment by javitonino** [comment]
It fixed itself after a while (15 minutes). However, it'd still be nice to investigate why this happens and gets cached in the repository, etc. See if there is a better option. No longer urgent, so moving to backlog.

**Comment by alrocar** [comment]
👋
