### ISSUE TITLE
Issue when running any task

### ISSUE THREAD

**Issue by stevelacy** [CartoDB/bigmetadata#606]
Following the quick start exactly I am left with:
```
root@bigmetadata-1:~/bigmetadata# make -- run es.ine.FiveYearPopulation
python3 -m luigi  --module tasks.es.ine tasks.es.ine.FiveYearPopulation
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: type "geometry" does not exist
LINE 6:  the_geom GEOMETRY (GEOMETRY, 4326),
```

```
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS                     NAMES
0d4afe6add5e        carto/bigmetadata               "/bigmetadata/conf/d…"   About an hour ago   Up About an hour    0.0.0.0:32778->8082/tcp   bigmetadata_bigmetadata_daemon_1
31e00fdf8d41        carto/bigmetadata_postgres_10   "docker-entrypoint.sh"   About an hour ago   Up About an hour    0.0.0.0:5432->5432/tcp    bigmetadata_postgres10_1
a011992b7fc9        nginx:latest                    "nginx -g 'daemon of…"   About an hour ago   Up About an hour    0.0.0.0:32772->80/tcp     bigmetadata_nginx_1
```

All `run` tasks fail as the following:
```
$ make docker-uk-all

root@bigmetadata-1:~/bigmetadata# docker logs fa3b567235db
wait-for-it.sh: waiting 15 seconds for postgres10:5432
wait-for-it.sh: postgres10:5432 is available after 0 seconds
make -- run uk.cdrc.CDRCMetaWrapper
make[1]: Entering directory '/bigmetadata'
python3 -m luigi  --module tasks.uk.cdrc tasks.uk.cdrc.CDRCMetaWrapper
Makefile:29: recipe for target 'run' failed
make[1]: *** [run] Error 1
make[1]: Leaving directory '/bigmetadata'
Makefile:377: recipe for target 'uk-geo-cdrc' failed
make: *** [uk-geo-cdrc] Error 2
```

What other commands or readme should I be following?

**Comment by stevelacy** [comment]
Any solution for this?
