### ISSUE TITLE
Can't build uk.cdrc OutputAreas

### ISSUE THREAD

**Issue by aspcanada** [CartoDB/bigmetadata#80]
I can’t seem to get the following task working: `make -- run uk.cdrc OutputAreas`

Here is the error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/luigi/worker.py", line 177, in run
    new_deps = self._run_get_new_deps()
  File "/usr/local/lib/python2.7/dist-packages/luigi/worker.py", line 115, in _run_get_new_deps
    task_gen = self.task.run()
  File "/bigmetadata/tasks/util.py", line 1187, in run
    self.populate()
  File "/bigmetadata/tasks/uk/cdrc.py", line 104, in populate
    input=self.input()['data'].table,
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1044, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 947, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 262, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1055, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1191, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1386, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1184, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (psycopg2.ProgrammingError) INSERT has more expressions than target columns
LINE 1: ...4dd7359 SELECT ST_MakeValid(wkb_geometry), oa_sa, sprgrp, gr...
                                                             ^
 [SQL: 'INSERT INTO observatory.obs_22ef53ead17e44478fb65e19006722b304dd7359 SELECT ST_MakeValid(wkb_geometry), oa_sa, sprgrp, grp, subgrp FROM "uk.cdrc".ImportOutputAreas__99914b932b']
rollback OutputAreas__99914b932b: (psycopg2.ProgrammingError) INSERT has more expressions than target columns
LINE 1: ...4dd7359 SELECT ST_MakeValid(wkb_geometry), oa_sa, sprgrp, gr...
                                                             ^
 [SQL: 'INSERT INTO observatory.obs_22ef53ead17e44478fb65e19006722b304dd7359 SELECT ST_MakeValid(wkb_geometry), oa_sa, sprgrp, grp, subgrp FROM "uk.cdrc".ImportOutputAreas__99914b932b']
INFO: Skipping error email. Set `error-email` in the `core` section of the luigi config file or override `owner_email`in the task to receive error emails.
INFO: Informed scheduler that task   OutputAreas__99914b932b   has status   FAILED
```

**Comment by talos** [comment]
Resolved with 4edb621ce456fb048c0e7fbd48bec7c9748df4b8.
